### ISSUE TITLE
project not work

### ISSUE THREAD

**Issue by EdisonLiao** [cemuka/basic-merge-system#1]
I import it into unity and press play button, click where but no use to create new chicken, it just like no active

**Comment by EdisonLiao** [comment]
what my project look like
![image](https://user-images.githubusercontent.com/14108176/148086349-6108e061-59f0-4655-9262-82c984c3abcb.png)

**Comment by cemuka** [comment]
Just press space button on your keyboard.

**Comment by EdisonLiao** [comment]
> Just press space button on your keyboard.

thank you
